# Generated by Django 3.2.4 on 2021-07-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='massage',
            new_name='message',
        ),
    ]
